# Note: For production. For development, use `docker-compose.dev.yml`
version: '3.3'
services:
  reactql-dev:
    build: .
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - 4000:4000
    environment:
      HOST: "0.0.0.0"
      BROWSER_HOST: "0.0.0.0"
