query Gallery($id: Int!, $token: String!, $page: Int=0) {
  getGallery(id: $id, token: $token) {
    id
    token
    title
    tags
    category
    thumbnailUrl
    imagesPage(page: $page) {
      pageInfo {
        total
        hasNextPage
        page
      }
      images {
        id
        token
        galleryId
        pageNumber
        thumbnailUrl
        name
      }
    }
  }
}
