query Gallery($id: Int!, $token: String!) {
  getGallery(id: $id, token: $token) {
    id
    token
    title
    tags
    thumbnailUrl
    imagesPage {
      pageInfo {
        total
      }
      images {
        id
        token
        galleryId
        pageNumber
        thumbnailUrl
        name
      }
    }
  }
}
