query Image($galleryId: Int!, $token: String!, $pageNumber: Int!) {
  getImage(galleryId: $galleryId, token: $token, pageNumber: $pageNumber) {
    id
    galleryId
    token
    pageNumber
    name
    fileUrl
    fileHeight
    fileWidth
    previousImage {
      id
      galleryId
      token
      pageNumber
    }
    nextImage {
      id
      galleryId
      token
      pageNumber
    }
  }
}
